### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#195]
@geekplux @ben-29 @shaonianche what we can do.
- [ ] 地图上虚线作为可选项
- [ ] 考虑换成 next.js
- [ ] fix all alert
- [ ] python code refactor
- [ ] pnpm consider?
- [ ] 性能提升
- [ ] doc improve
- [ ] geojson support
- [ ] rss3 maybe
- [ ] #122 
- [ ] more status char
- [ ] iOS app new --> GitHubPoster
- [ ] oppo
- [ ] #187
