### ISSUE TITLE
[TODO] garmin_to_garmin

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#261]
佳明和佳明中国同步设计

- [ ] 登陆 2 个账号，garmin and garmin-cn 两个对象
- [ ] garmin.get_last_time () and garmin_cn.get_last_time()
- [ ] 拿到两个 time 之间的 gpx upload to others
- [ ] ？是否需要重新设计 gpx 命名
--- 
局限
- [ ] garmin 限制了登陆，目前可能用 session 好一些，增加了用户的学习成本
- [ ] 如果中间有遗漏得重来
- [ ] 可能得重新设计 gpx 命名
- [ ] 先仅仅限制跑步的 type

**Comment by xiang578** [comment]
期待这个功能

**Comment by yihong0618** [comment]
@laihj 现在支持了 gramin_to_strava 你可以实验一下。

**Comment by laihj** [comment]
@yihong0618 
请问同时配置两个是怎么处理的？
`RUN_TYPE: garmin_cn/garmin_to_strava_cn `
这样好像不行

**Comment by yihong0618** [comment]
只能配置一个，并且最好是 cn

**Comment by keepup** [comment]
可参考 https://github.com/gooin/DailySync

**Comment by yihong0618** [comment]
@keepup 感谢
其实我后来搞定了，没更新的原因是 garmin-com 的安全策略，不保证每次成功(^-^)

**Comment by yihong0618** [comment]
@all 支持了
感谢 @NaturezzZ

**Comment by NoZTurn** [comment]
> [@yihong0618](https://github.com/yihong0618) 请问同时配置两个是怎么处理的？ `RUN_TYPE: garmin_cn/garmin_to_strava_cn ` 这样好像不行

我也想同时执行两个动作，不知道现在还是否有可行性。
